允许下载文件的名称与上传文件的名称保持一致
tryzealot/zealot pull request #1744
Opened 2024-11-27 01:56 UTC by rakuyoMo

施工中，自认为全部完成后会正式请求 review。

关联 issue https://github.com/tryzealot/zealot/issues/1611#issuecomment-2492843875 ，拟作为https://github.com/tryzealot/zealot/issues/1735 的临时解决方案。

> 我只会一些 ruby 的皮毛，更未涉足过 Ruby on Rails。如果任何人有什么建议或者发现了什么问题，请随时和我沟通，谢谢您的帮助！

2024-11-27 03:43 UTC, icyleaf commented
一点想法：

1. 把选项放到 release 每上传一次都要传一次是不是太麻烦了，不如放到上一层 channel 会更好一些。
1. 原 issue 如果也提 PR 那岂不是又要多一个字段，而且都设置 true 怎么办，不如改成一个枚举字段 :D

现在应用的三层结构在定义一些设置有些繁琐，太粗太细都不合适，之前有计划规划设置 policy 模板，可以随意 apply 到任意一层，鉴于时间精力也不盈利的情况下一直在鸽

2024-11-27 10:15 UTC, rakuyoMo commented
@icyleaf 我自认为完成了相关逻辑，现在可以开始 review 了。

2024-11-27 10:15 UTC, rakuyoMo commented on app/models/channel.rb
> +  }
@icyleaf 这里有个小问题，目前展示时会显示 "system" 或 "original"。因为这部分逻辑是参考 `device_type` 实现的，所以我不太确定在展示时如何更好地语义化处理。

2024-11-27 10:21 UTC, rakuyoMo commented on app/models/release.rb
> +    end
这里或许应该改成 `case channel.download_filename_type.downcase.to_sym` 更好？ 🤔

2024-11-27 13:58 UTC, icyleaf commented on app/models/release.rb
> +    end
文件名可以通过 `file.identifier` 获取

2024-11-27 14:17 UTC, icyleaf reviewed
会 Ruby 基本就会 Rails，别忘了 Rails 可以从入门到 IPO 的 slogan 😆

2024-11-27 14:17 UTC, icyleaf commented on app/models/channel.rb
> +    system: 'system',
最好加一个注解说明第一个 key-value 的位置不变，否则还需要新增一个 `DEFAULT_DOWNLOAD_FILENAME_TYPE` 去关联 `set_default_download_filename_type` callback 方法

2024-11-27 14:17 UTC, icyleaf commented on config/locales/simple_form/simple_form.zh-CN.yml
> +        download_filename_type: 下载文件文件名
下载文件文件名类型

2024-11-28 02:18 UTC, rakuyoMo commented on app/views/channels/_metadata.html.slim
> +      span.text-muted = t("channels.show.download_filename_type_item.#{@channel.download_filename_type}")
这里我增加了一行关于当前规则的文字说明，效果如下：

![image](https://github.com/user-attachments/assets/a4184980-8d1e-46f5-9894-313f97435914)
![image](https://github.com/user-attachments/assets/f193e87e-ef79-423b-b157-c99269f2f4f0)

几个想法：

1. 是否需要加该说明？我觉得加一下比较好
2. `version_datetime` 规则时，展示完整规则是否过长？但是这样确实比较清晰
3. 具体文言是否需要调整，“当前规则” 字样在第二行还是第三行比较好？

2024-11-28 02:20 UTC, rakuyoMo commented on config/locales/simple_form/simple_form.zh-CN.yml
> +        download_filename_type: 下载文件文件名
done

2024-11-28 02:20 UTC, rakuyoMo commented on app/models/channel.rb
> +    system: 'system',
已增加 `DEFAULT_DOWNLOAD_FILENAME_TYPE`

2024-11-28 02:21 UTC, rakuyoMo commented on app/models/release.rb
> +    end
1. 文件名改为通过 `file.identifier` 获取
2. `download_filename` 方法内改为使用 `case` 语法

2024-11-28 02:21 UTC, rakuyoMo commented on app/models/channel.rb
> +  }
已经对 `download_filename_type` 的成员进行重命名

2024-11-28 02:22 UTC, rakuyoMo commented on app/views/channels/_metadata.html.slim
> +      span.text-muted = t("channels.show.download_filename_type_item.#{@channel.download_filename_type}")
几个想法：

是否需要加该说明？我觉得加一下比较好
version_datetime 规则时，展示完整规则是否过长？但是这样确实比较清晰
具体文言是否需要调整，“当前规则” 字样在第二行还是第三行比较好？

2024-11-28 04:02 UTC, icyleaf commented on app/views/channels/_metadata.html.slim
> +      span.text-muted = t("channels.show.download_filename_type_item.#{@channel.download_filename_type}")
> 是否需要加该说明？我觉得加一下比较好

可以加，样式上建议稍微调整下，当前设计是键值对的简洁输出，不太建议把 key 搞成 description，描述的内容可以用提示的方式做，搜索代码 `data-bs-toggle="tooltip"` 参考。

2024-11-28 05:33 UTC, rakuyoMo commented on app/views/channels/_metadata.html.slim
> +      span.text-muted = t("channels.show.download_filename_type_item.#{@channel.download_filename_type}")
done.

已完成全部修改建议，请求进一步审查或合并。

2024-11-29 01:43 UTC, icyleaf commented on config/locales/zealot/zh-CN.yml
> +      download_filename_type: 下载文件的文件名生成规则
同上：下载文件名规则

2024-11-29 05:17 UTC, rakuyoMo commented on config/locales/zealot/en.yml
> +      download_filename_type: File name generation rules for downloaded file
done

2024-11-29 05:17 UTC, rakuyoMo commented on config/locales/zealot/zh-CN.yml
> +      download_filename_type: 下载文件的文件名生成规则
done

2024-11-29 08:06 UTC, rakuyoMo commented on db/migrate/20241127143631_add_download_file_type_to_channel.rb
> +  def change
这里设置默认值的时候是不是不能用 `Channel.DEFAULT_DOWNLOAD_FILENAME_TYPE` 了，得用字符串+注释的形式了吧？

2024-11-29 08:20 UTC, rakuyoMo commented on db/migrate/20241127143631_add_download_file_type_to_channel.rb
> +  def change
https://github.com/tryzealot/zealot/pull/1744/commits/6ff8cf5a3cca55264190eb1041f871bd865cef72 按照注释+硬编码字符串实现

2024-11-29 10:23 UTC, icyleaf requested changes
修改完这个就可以合并了 😄

2024-11-29 10:23 UTC, icyleaf commented on db/migrate/20241127143631_add_download_file_type_to_channel.rb
Change to this code: 

```ruby
# frozen_string_literal: true

class AddDownloadFileTypeToChannel < ActiveRecord::Migration[7.2]
  def change
    add_column :channels, :download_filename_type, :string

    reversible do |dir|
      dir.up do
        # update previous the value of download_filename_type
        Channel.where(download_filename_type: nil).each do |channel|
          channel.update!(download_filename_type: Channel::DEFAULT_DOWNLOAD_FILENAME_TYPE) 
        end
      end
    end
  end
end
```

2024-11-30 01:10 UTC, rakuyoMo commented on db/migrate/20241127143631_add_download_file_type_to_channel.rb
done~

2024-11-30 02:45 UTC, icyleaf approved these changes
LGTM

2024-11-30 02:47 UTC, merged